language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1-Denisov-labs
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
  - ./Stack/Stack
  - ./StackTest/StackTest
notifications:
  email: false
